const SIDE_BAR='SIDE_BAR'
const VIEW_MODE_LIGHT='VIEW_MODE_LIGHT'
const VIEW_MODE_DARK='VIEW_MODE_DARK'
const VIEW_MODE_AUTO='VIEW_MODE_AUTO'
const VIEW_LANGUAGE_VI='VIEW_LANGUAGE_VI'
const VIEW_LANGUAGE_EN='VIEW_LANGUAGE_EN'

const actionTypes={
    SIDE_BAR,
    VIEW_MODE_LIGHT,
    VIEW_MODE_DARK,
    VIEW_MODE_AUTO,
    VIEW_LANGUAGE_VI,
    VIEW_LANGUAGE_EN,
}

export default actionTypes